config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :entities, only: %i[new create]

  resources :managers, only: %i[new create destroy] do
    collection do
      # manager sessions
      get 'sessions/new', to: 'manager_sessions#new', as: :sign_in
      post 'sessions', to: 'manager_sessions#create'
      delete 'session', to: 'manager_sessions#destroy', as: :sign_out

      # manager invitations
      get 'invitations/:token',
          to: 'manager_invitations#new',
          as: :new_invitation
      patch 'invitations', to: 'manager_invitations#update'
    end
  end

  get 'passwords/lost', to: 'passwords#new', as: :new_password
  post 'passwords', to: 'passwords#create'
  get 'passwords/renew/:token', to: 'passwords#edit', as: :renew_password
  patch 'passwords', to: 'passwords#update'

  resources :services do
    resources :service_referees, only: %i[new create destroy]
    resources :assignations, only: [] do
      collection do
        delete :disable_notifications
        post :enable_notifications
      end
    end
  end
  get "/services/qrcode/:token",
      to: "services#qrcode",
      as: :service_qrcode
  get 'services/:id/:token', to: 'services#show'

  get "/entities/availabilities/:token",
      to: "entities#availabilities",
      as: :entity_availabilities
  get "/entities/qrcode/:token",
      to: "entities#qrcode",
      as: :entity_qrcode
  get "/services/availabilities/edit/:token",
      to: "services#edit_availabilities",
      as: :edit_availabilities
  patch "/services/availabilities/:token",
        to: "services#update_availabilities",
        as: :update_availabilities
  post "/services/notification_subscriptions/:token",
       to: "notification_subscriptions#create",
       as: :notification_subscriptions
  delete "/services/notification_subscriptions/:token",
         to: "notification_subscriptions#destroy",
         as: :delete_notification_subscriptions

  require 'sidekiq/web'
  require 'sidekiq/cron/web'
  # Sidekiq::Web.set :session_secret, Rails.application.credentials[:secret_key_base]
  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    ActiveSupport::SecurityUtils
      .secure_compare(
        ::Digest::SHA256.hexdigest(username),
        ::Digest::SHA256.hexdigest(ENV["SIDEKIQ_USERNAME"])
      ) &
      ActiveSupport::SecurityUtils.secure_compare(
        ::Digest::SHA256.hexdigest(password),
        ::Digest::SHA256.hexdigest(ENV["SIDEKIQ_PASSWORD"])
      )
  end
  mount Sidekiq::Web => '/sidekiq'

  get "/scanner", to: "pages#qrcode_scanner", as: "qrcode_scanner"
  root to: "pages#home"

end

app/models/service.rb
class Service < ApplicationRecord

  has_secure_token :token

  %i[
    total_bed_count
    available_women_bed_count
    available_man_bed_count
    available_gender_free_bed_count
    available_isolated_bed_count
  ].each do |attribute|
    validates attribute,
              presence: true,
              numericality: { greater_than_or_equal_to: 0 }
  end

  validates :name, presence: true
  validates :token, uniqueness: true
  validate :total_beds_should_be_less_than_availables
  validate :verify_planned_vs_available, on: :update

  has_many :notification_subscriptions,
           dependent: :destroy,
           inverse_of: :service
  has_many :assignations, dependent: :destroy
  has_many :service_referees,
           dependent: :destroy,
           through: :assignations,
           inverse_of: :services do
             def notifiable
               where("assignations.accept_notifications = ?", true)
             end
           end
  belongs_to :entity, inverse_of: :services

  def sum_available_beds
    countable_attibutes = %w[
      available_women_bed_count
      available_man_bed_count
      available_gender_free_bed_count
      available_isolated_bed_count
    ]

    attributes.slice(*countable_attibutes).values.compact.sum
  end

  def self.generate_unique_secure_token
    SecureRandom.base58(45)
  end

  def notify(count = 0)
    elapsed_time = (Time.zone.now - self.updated_at) / 60
    return if elapsed_time < 30 + 30 * count.to_i

    emails = []
    emails += self.service_referees.notifiable.map(&:email)
    notif_create_column = NotificationSubscription.arel_table[:created_at]
    emails += self.notification_subscriptions
      .where(notif_create_column.gt(24.hours.ago))
      .map(&:email)

    return if emails.empty?

    NotificationMailer.with(
      service: self,
      emails: emails.uniq
    ).notify.deliver
  end

  private

  def total_beds_should_be_less_than_availables
    return if sum_available_beds <= (total_bed_count || 0)

    errors.add(:base, I18n.t('activerecord.errors.service.invalid_total'))
  end

  def verify_planned_vs_available
    return unless current_availability.present? &&
                  planned_arrivals_count.present? &&
                  planned_leaves_count.present?

    if sum_available_beds <=
       (current_availability.to_i +
        planned_leaves_count.to_i -
        planned_arrivals_count.to_i)
      return
    end

    errors.add(:base, I18n.t('activerecord.errors.service.missmatch_total'))
  end

end

app/controllers/services_controller.rb
class ServicesController < ApplicationController

  before_action :require_login,
                except: %i[
                  edit_availabilities
                  update_availabilities
                  qrcode
                  show
                ]

  def index
    @services = current_entity&.services
    redirect_to root_url && return unless @services

    @services = @services
      .includes(:service_referees)
      .order(floor: :asc, name: :asc)
  end

  def new
    @service = current_entity&.services&.build
    redirect_to root_url unless @service
  end

  def create
    @service = current_entity&.services&.build(permitted_params_for_create)
    redirect_to root_url && return unless @service

    if @service.save
      redirect_to services_url,
                  flash: { success: t('services.flash.create.success') }
      return
    end

    flash[:error] = t('services.flash.create.error')
    render :new
  end

  def edit
    @service = current_entity&.services&.find_by(id: params[:id])
    redirect_to root_url unless @service
  end

  def update
    @service = current_entity&.services&.find_by(id: params[:id])
    redirect_to root_url && return unless @service

    if @service.update(permitted_params_for_create)
      redirect_to services_url,
                  flash: { success: t('services.flash.update.success') }
      return
    end

    flash[:error] = t('services.flash.update.error')
    render :new
  end

  def destroy
    service = current_entity&.services&.find_by(id: params[:id])
    redirect_to root_url && return unless service

    if service.destroy
      flash[:success] = t('services.flash.destroy.success')
    else
      flash[:error] = t('services.flash.destroy.error')
    end

    redirect_to services_url
  end

  def edit_availabilities
    @service = Service.where(token: params[:token]).first

    if @service
      @notification_subscription =
        NotificationSubscription
          .where(id: get_notification_subscription_id(@service)).first ||
        @service.notification_subscriptions.build
    else
      redirect_to root_path
    end
  end

  def update_availabilities
    @service = Service.where(token: params[:token]).first
    unless @service
      redirect_to root_path
      return
    end

    if @service.update(permitted_params_for_update) && @service.touch
      flash[:success] = t('services.flash.availabilities.success')
      redirect_to edit_availabilities_path(token: @service.token)
    else
      @step_2 = true
      flash[:error] = t('services.flash.availabilities.error')
      render :edit_availabilities
    end
  end

  def qrcode
    @service = Service.where(token: params[:token]).first
    redirect_to root_url unless @service
  end

  def show
    @entity = Entity.where(token: params[:token]).first
    @service = @entity.services.where(id: params[:id]).first if @entity
    redirect_to root_url unless @service
  end

  private

  def permitted_params_for_update
    params.require(:service).permit(
      :current_availability,
      :planned_leaves_count,
      :planned_arrivals_count,
      :available_women_bed_count,
      :available_man_bed_count,
      :available_gender_free_bed_count,
      :available_isolated_bed_count,
      :update_comment
    )
  end

  def permitted_params_for_create
    params
      .require(:service)
      .permit(:name, :floor, :total_bed_count, :comment, :uds)
  end

end

app/views/services/_fields.html.erb
<div class="form-group">
  <%= f.label :name, t('.name') %>
  <%= f.text_field :name %>
</div>

<div class="form-group">
  <%= f.label :floor, t('.floor') %>
  <%= f.number_field :floor %>
</div>

<div class="form-group">
  <%= f.label :total_bed_count, t('.total_bed_count') %>
  <%= f.number_field :total_bed_count %>
</div>

<div class="form-group">
  <%= f.label :comment, t('.comment') %>
  <%= f.text_area :comment %>
</div>
<div class="form-group">
  <%= f.label :contact, t('.contact') %>
  <%= f.text_area :contact %>
</div>

<div class="form-group">
  <%= f.label :uds, t('.uds') %>
  <%= f.text_field :uds %>
</div>

app/views/services/edit.html.erb
<h1>
  <%= current_entity.name %>
</h1>

<h2>
  <%= t('.title')%>
</h2>

<div class="form_service_creation">
  <%= form_for(@service) do |f| %>

    <% if f.object.errors.any? %>
      <div class="flash alert errors">
        <p>
          <%= t('.errors_count', count: f.object.errors.count) %>
        </p>
        <ul>
          <% f.object.errors.full_messages.each do |msg| %>
            <li>
              <%= msg %>
            </li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <%= render partial: 'fields', locals: { f: f } %>

    <p class="submit-container">
      <%= f.submit t('.submit') %>
    </p>
  <% end %>

</div>

app/views/services/edit_availabilities.html.erb
<h1><%= @service.entity.name %></h1>

<h2><%= t('.service_title', service: @service.name) %></h2>

<% if current_user %>
  <div class="new_subscription">
    <p class="new_subscription_switch">
      <%= t('.new_subscription_title')%>
    </p>
    <% if @service.assignations.where(service_referee: current_user, accept_notifications: true).exists? %>
      <p><%= t('.current_subscription', email: current_user.email) %>&nbsp;-&nbsp;<%= link_to t('.unsubscribe'), disable_notifications_service_assignations_url(@service), method: :delete, data: { confirm: t('.unsubscribe_why_not') } %>
      </p>
    <% else %>
      <p><%= link_to t('.subscribe'), enable_notifications_service_assignations_url(@service), method: :post %></p>
    <% end %>
  </div>
<% else %>
  <div class="new_subscription">
    <p class="new_subscription_switch">
      <%= t('.new_subscription_title')%>
    </p>
    <% if @notification_subscription.new_record? %>
      <%= form_for @notification_subscription, url: notification_subscriptions_path, html: { id: "notification-form" } do |form| %>
        <div class="form-group">
          <%= form.label :email %>
          <%= form.email_field :email %>
        </div>
        <p class="submit-container">
          <%= form.submit t('.subscribe') %>
        </p>
      <% end %>
    <% else %>
      <p><%= t('.current_subscription', email: @notification_subscription.email) %>&nbsp;-&nbsp;<%= link_to t('.unsubscribe'), delete_notification_subscriptions_path(@service.token, id: @notification_subscription), method: :delete, data: { confirm: t('.unsubscribe_why_not') } %>
    <% end %>
  </div>
<% end %>

<p class="last_update <%= (Time.zone.now - @service.updated_at) / 60 < 10 ? 'recent' : '' %>">
  <%= t('.last_update_html', time: l(@service.updated_at)) %>
</p>
<p class="total_availability">
  <%= t('.total_beds_html', count: @service.total_bed_count) %>
</p>

<%= form_for @service, url: update_availabilities_path, html: { id: "quick-update-form" } do |form| %>
    <%= form.hidden_field :available_women_bed_count %>
    <%= form.hidden_field :available_man_bed_count %>
    <%= form.hidden_field :available_gender_free_bed_count %>
    <%= form.hidden_field :available_isolated_bed_count %>
    <p class="submit-container">
      <%= form.submit t('.no_changes') %>
    </p>
<% end %>

<p>
  <%= link_to t('.see_info'), service_url(@service, token: @service.entity.token) %>
</p>

<%= form_for @service, url: update_availabilities_path, html: { id: "service-update-form" } do |form| %>
  <div class="step" id="service_update_step1" style="display:<%= @step_2 ? 'none' : 'block' %>;">
    <div class="flash alert errors" id="service_update_step1_errors">
      <p>
        <%= t('.verification_errors') %>
      </p>
    </div>
    <div class="form-group">
      <%= form.label :current_availability %>
      <%= form.number_field :current_availability, pattern: "[0-9]*", inputmode: "numeric" %>
    </div>
    <div class="form-group">
      <%= form.label :planned_leaves_count %>
      <%= form.number_field :planned_leaves_count, pattern: "[0-9]*", inputmode: "numeric" %>
    </div>
    <div class="form-group">
      <%= form.label :planned_arrivals_count %>
      <%= form.number_field :planned_arrivals_count, pattern: "[0-9]*", inputmode: "numeric" %>
    </div>
    <p class="submit-container">
      <%= form.submit t('.next'), id: "next_button" %>
    </p>
  </div>

  <div class="step" id="service_update_step2" style="display:<%= @step_2 ? 'block' : 'none' %>;">
    <p><%= t('.available_count_confirmation_html')%>
    <% if form.object.errors.any? %>
      <div class="flash alert errors">
        <p>
          <%= t('.errors_count', count: form.object.errors.count) %>
        </p>
        <ul>
          <% form.object.errors.full_messages.each do |msg| %>
            <li>
              <%= msg %>
            </li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="form-group with_icon">
      <%= image_tag('bed_woman.svg') %>
      <div>
        <%= form.label :available_women_bed_count %>
        <%= form.number_field :available_women_bed_count, pattern: "[0-9]*", inputmode: "numeric" %>
      </div>
    </div>
    <div class="form-group with_icon">
      <%= image_tag('bed_man.svg') %>
      <div>
        <%= form.label :available_men_bed_count %>
        <%= form.number_field :available_man_bed_count, pattern: "[0-9]*", inputmode: "numeric" %>
      </div>
    </div>
    <div class="form-group with_icon">
      <%= image_tag('bed_gender.svg') %>
      <div>
        <%= form.label :available_gender_free_bed_count %>
        <%= form.number_field :available_gender_free_bed_count, pattern: "[0-9]*", inputmode: "numeric" %>
      </div>
    </div>
    <div class="form-group with_icon">
      <%= image_tag('bed_isolated.svg') %>
      <div>
        <%= form.label :available_isolated_bed_count %>
        <%= form.number_field :available_isolated_bed_count, pattern: "[0-9]*", inputmode: "numeric" %>
      </div>
    </div>
    <div class="form-group">
      <%= form.label :update_comment %>
      <%= form.text_area :update_comment %>
    </div>
    <p class="submit-container">
      <%= form.submit t('.previous'), id: "previous_button" %>
      <%= form.submit t('.save') %>
    </p>
  </div>
<% end %>

app/views/services/index.html.erb
<h1><%= @current_entity.name %></h1>

<h2><%= t('.title') %></h2>

<div class="centered-button">
  <%= link_to t('.add_service'), new_service_url, class: 'button' %>
</div>

<table class="services-table service-informations">
  <thead>
    <tr>
      <th>
        <%= t('.floor') %>
      </th>
      <th>
        <%= t('.name') %>
      </th>
      <th>
        <%= t('.total_bed_count') %>
      </th>
      <th>
        <%= t('.service_referees') %>
      </th>
      <th>
        <%= t('.comment') %>
      </th>
      <th>
        <%= t('.uds') %>
      </th>
      <th>
        <%= t('.actions') %>
      </th>
    </tr>
  </thead>
  <tbody>
    <% @services.each do |service| %>
      <tr>
        <td><%= service.floor %></td>
        <td><%= link_to(service.name,
                        service_url(service,
                                    token: service.entity.token)) %></td>
        <td><%= service.total_bed_count%></td>
        <td><%= service.service_referees.map(&:name).join(', ') %></td>
        <td>
          <%= simple_format(service.comment) %><br />
          <%= simple_format(service.contact) %>
        </td>
        <td><%= service.uds %></td>
        <td class="actions">
          <%= link_to t('.manage_referees'), new_service_service_referee_path(service) %>
          <%= link_to t('.qrcode'), service_qrcode_path(service, token: service.token) %>
          <%= link_to t('.form'), edit_availabilities_path(service, token: service.token) %>
          <%= link_to t('.edit'), edit_service_path(service) %>
          <%= link_to t('.delete'),
                      service_path(service),
                      method: :delete,
                      data: { confirm: t('.why_not') } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/services/new.html.erb
<h1>
  <%= current_entity.name %>
</h1>

<h2>
  <%= t('.title')%>
</h2>

<div class="form_service_creation">
  <%= form_for(@service) do |f| %>

    <% if f.object.errors.any? %>
      <div class="flash alert errors">
        <p>
          <%= t('.errors_count', count: f.object.errors.count) %>
        </p>
        <ul>
          <% f.object.errors.full_messages.each do |msg| %>
            <li>
              <%= msg %>
            </li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <%= render partial: 'fields', locals: { f: f } %>

    <p class="submit-container">
      <%= f.submit t('.submit') %>
    </p>
  <% end %>

</div>

app/views/services/qrcode.html.erb
<h1><%= @service.entity.name %> - <%= @service.name %></h1>

<p><%= t('.explanation') %></p>

<h2><%= t('.emergency_qrcode') %></h2>

<div id="qrcode" data-url="<%=edit_availabilities_url(@service.token) %>">
</div>

app/views/services/show.html.erb
<h1><%= @service.entity.name %></h1>

<h2><%= t('.service_title', service: @service.name) %></h2>
<p>
  <%= t('.last_update_html', time: l(@service.updated_at)) %>
</p>

<h2><%= t('.service_stats') %></h2>

<%= render partial: "shared/stats", locals: { services: [@service] } %>

<h2><%= t('.information') %></h2>

<table class="services-table service-informations">
  <thead>
  </thead>
  <tbody>
    <tr>
      <td><%= t('.floor') %></td>
      <td><%= @service.floor %></td>
    </tr>
    <tr>
      <td><%= t('.total_bed_count') %></td>
      <td><%= @service.total_bed_count %></td>
    </tr>
    <tr>
      <td><%= t('.referees') %></td>
      <td>
        <ul>
          <% @service.service_referees.each do |referee| %>
            <li>
              <%= referee.name %> &lt;<%= link_to referee.email, "mailto:#{referee.email}" %>&gt;<br />
              <%= referee.contact_details%>
            </li>
          <% end %>
        </ul>
      </td>
    </tr>
    <tr>
      <td><%= t('.comment') %></td>
      <td>
        <%= simple_format(@service.comment) %><br />
      </tr>
    <tr>
      <td><%= t('.contact') %></td>
      <td>
        <%= simple_format(@service.contact) %>
      </td>
    </tr>
    <tr>
      <td><%= t('.uds') %></td>
      <td><%= @service.uds %></td>
    </tr>
  </tbody>
</table>