config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :entities, only: %i[new create]

  resources :managers, only: %i[new create destroy] do
    collection do
      # manager sessions
      get 'sessions/new', to: 'manager_sessions#new', as: :sign_in
      post 'sessions', to: 'manager_sessions#create'
      delete 'session', to: 'manager_sessions#destroy', as: :sign_out

      # manager invitations
      get 'invitations/:token',
          to: 'manager_invitations#new',
          as: :new_invitation
      patch 'invitations', to: 'manager_invitations#update'
    end
  end

  get 'passwords/lost', to: 'passwords#new', as: :new_password
  post 'passwords', to: 'passwords#create'
  get 'passwords/renew/:token', to: 'passwords#edit', as: :renew_password
  patch 'passwords', to: 'passwords#update'

  resources :services do
    resources :service_referees, only: %i[new create destroy]
    resources :assignations, only: [] do
      collection do
        delete :disable_notifications
        post :enable_notifications
      end
    end
  end
  get "/services/qrcode/:token",
      to: "services#qrcode",
      as: :service_qrcode
  get 'services/:id/:token', to: 'services#show'

  get "/entities/availabilities/:token",
      to: "entities#availabilities",
      as: :entity_availabilities
  get "/entities/qrcode/:token",
      to: "entities#qrcode",
      as: :entity_qrcode
  get "/services/availabilities/edit/:token",
      to: "services#edit_availabilities",
      as: :edit_availabilities
  patch "/services/availabilities/:token",
        to: "services#update_availabilities",
        as: :update_availabilities
  post "/services/notification_subscriptions/:token",
       to: "notification_subscriptions#create",
       as: :notification_subscriptions
  delete "/services/notification_subscriptions/:token",
         to: "notification_subscriptions#destroy",
         as: :delete_notification_subscriptions

  require 'sidekiq/web'
  require 'sidekiq/cron/web'
  # Sidekiq::Web.set :session_secret, Rails.application.credentials[:secret_key_base]
  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    ActiveSupport::SecurityUtils
      .secure_compare(
        ::Digest::SHA256.hexdigest(username),
        ::Digest::SHA256.hexdigest(ENV["SIDEKIQ_USERNAME"])
      ) &
      ActiveSupport::SecurityUtils.secure_compare(
        ::Digest::SHA256.hexdigest(password),
        ::Digest::SHA256.hexdigest(ENV["SIDEKIQ_PASSWORD"])
      )
  end
  mount Sidekiq::Web => '/sidekiq'

  get "/scanner", to: "pages#qrcode_scanner", as: "qrcode_scanner"
  root to: "pages#home"

end

app/views/shared/_auth_links.html.erb
<% if controller_name == 'manager_sessions' %>
  <p>
    <%= link_to t('.forgot_password'), new_password_url %>
  </p>
<% end %>
<% if controller_name == 'passwords' %>
  <p>
    <%= link_to t('.sign_in'), sign_in_managers_url %>
  </p>
<% end %>

app/views/shared/_install_permission.html.erb
  <div class="flash warning">
    <p>Nous vous recommandons d'installer l'application pous plus de facilité à la retrouver.</p>
    <p><a class="button" id="installation-button">Installer l'application</a></p>
  </div>

app/views/shared/_menu.html.erb
<ul id="menu" class="dropdown">
  <li class="trigger">
  <%= link_to t('.menu'), '#', class: "dropdown_head" %>
  </li>
  <div class="dropdown_content">
    <li><%= link_to(t('.home'), root_url) %></li>
    <li><%= link_to(t('.scanner'), qrcode_scanner_url) %></li>
    <% if current_user %>
      <li><%= link_to(t('.availabilities'), entity_availabilities_url(current_user.entity.token)) %></li>
      <% if current_user.is_a?(ServiceReferee) %>
        <li>
          <%= t('.service') %>
          <div>
            <ul>
              <% current_user.services.each do |s| %>
                <%= link_to(s.name, service_url(s, token: current_user.entity.token)) %>
              <% end %>
            </ul>
          </div>
        </li>
        <li>
          <%= t('.service_qrcode') %>
          <div>
            <ul>
              <% current_user.services.each do |s| %>
                <%= link_to(s.name, service_qrcode_url(s.token)) %>
              <% end %>
            </ul>
          </div>
        </li>
        <li>
          <%= t('.service_availabilities') %>
          <div>
            <ul>
              <% current_user.services.each do |s| %>
                <%= link_to(s.name, edit_availabilities_url(s.token)) %>
              <% end %>
            </ul>
          </div>
        </li>
      <% else %>
        <li><%= link_to(t('.entity_qrcode'), entity_qrcode_url(current_user.entity.token)) %></li>
        <li><%= link_to(t('.services'), services_url) %></li>
        <li><%= link_to(t('.managers'), new_manager_url) %></li>
      <% end %>
      <li><%= link_to(t('.manager_out'), sign_out_managers_url, method: :delete) %></li>
    <% else %>
      <li><%= link_to(t('.manager_sign_up'), new_entity_url) %></li>
      <li><%= link_to(t('.manager_login'), sign_in_managers_url) %></li>
    <% end %>
  </div>
</ul>

app/views/shared/_notification_permission.html.erb
<% content_for(:notification_permission) do %>
  <div class="flash warning">
    <p>On vous recommande d'autoriser les notifications pour cette application. De cette façon, vous serez automatiquement rappelés de mettre à jour la disponibilité des lits de votre service, ou averti de nouvelles demandes et disponibilités</p>
    <p><a class="button" id="notifications-permission-request">Autoriser les notifications</a></p>
  </div>
<% end %>

app/views/shared/_stats.html.erb
<% total_existing_beds = services.inject(0) { |a, s| a += s.total_bed_count } %>
<% total_available_beds = services.inject(0) { |a, s| a += s.available_women_bed_count + s.available_man_bed_count + s.available_gender_free_bed_count + s.available_isolated_bed_count } %>
<% color_class = color_class(total_available_beds, total_existing_beds) %>

<div class="info-box total-box">
  <dl>
      <!-- <p class="picto_description">Total de lits disponibles</p> -->
    <div>
      <dt><%= image_tag('bed.svg') %></dt>
      <dd class="<%= color_class %>"><%= total_available_beds %></dd>
    </div>
  </dl>

</div>

<div class="info-box split-box">
  <dl>
    <div>
      <dt><%= image_tag('bed_woman.svg') %></dt>
      <dd class="<%= color_class %>">
        <%= services.inject(0) { |a, s| a+= s.available_women_bed_count } %>
      </dd>
    </div>
    <div>
      <dt><%= image_tag('bed_man.svg') %></dt>
      <dd class="<%= color_class %>">
        <%= services.inject(0) { |a, s| a+= s.available_man_bed_count } %>
      </dd>
    </div>
    <div>
      <dt><%= image_tag('bed_gender.svg') %></dt>
      <dd class="<%= color_class %>">
        <%= services.inject(0) { |a, s| a+= s.available_gender_free_bed_count } %>
      </dd>
    </div>
    <div>
      <dt><%= image_tag('bed_isolated.svg') %></dt>
      <dd class="<%= color_class %>">
        <%= services.inject(0) { |a, s| a+= s.available_isolated_bed_count } %>
      </dd>
    </div>
  </dl>
</div>