config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :entities, only: %i[new create]

  resources :managers, only: %i[new create destroy] do
    collection do
      # manager sessions
      get 'sessions/new', to: 'manager_sessions#new', as: :sign_in
      post 'sessions', to: 'manager_sessions#create'
      delete 'session', to: 'manager_sessions#destroy', as: :sign_out

      # manager invitations
      get 'invitations/:token',
          to: 'manager_invitations#new',
          as: :new_invitation
      patch 'invitations', to: 'manager_invitations#update'
    end
  end

  get 'passwords/lost', to: 'passwords#new', as: :new_password
  post 'passwords', to: 'passwords#create'
  get 'passwords/renew/:token', to: 'passwords#edit', as: :renew_password
  patch 'passwords', to: 'passwords#update'

  resources :services do
    resources :service_referees, only: %i[new create destroy]
    resources :assignations, only: [] do
      collection do
        delete :disable_notifications
        post :enable_notifications
      end
    end
  end
  get "/services/qrcode/:token",
      to: "services#qrcode",
      as: :service_qrcode
  get 'services/:id/:token', to: 'services#show'

  get "/entities/availabilities/:token",
      to: "entities#availabilities",
      as: :entity_availabilities
  get "/entities/qrcode/:token",
      to: "entities#qrcode",
      as: :entity_qrcode
  get "/services/availabilities/edit/:token",
      to: "services#edit_availabilities",
      as: :edit_availabilities
  patch "/services/availabilities/:token",
        to: "services#update_availabilities",
        as: :update_availabilities
  post "/services/notification_subscriptions/:token",
       to: "notification_subscriptions#create",
       as: :notification_subscriptions
  delete "/services/notification_subscriptions/:token",
         to: "notification_subscriptions#destroy",
         as: :delete_notification_subscriptions

  require 'sidekiq/web'
  require 'sidekiq/cron/web'
  # Sidekiq::Web.set :session_secret, Rails.application.credentials[:secret_key_base]
  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    ActiveSupport::SecurityUtils
      .secure_compare(
        ::Digest::SHA256.hexdigest(username),
        ::Digest::SHA256.hexdigest(ENV["SIDEKIQ_USERNAME"])
      ) &
      ActiveSupport::SecurityUtils.secure_compare(
        ::Digest::SHA256.hexdigest(password),
        ::Digest::SHA256.hexdigest(ENV["SIDEKIQ_PASSWORD"])
      )
  end
  mount Sidekiq::Web => '/sidekiq'

  get "/scanner", to: "pages#qrcode_scanner", as: "qrcode_scanner"
  root to: "pages#home"

end

app/controllers/manager_invitations_controller.rb
class ManagerInvitationsController < ApplicationController

  def new
    @manager = Manager.find_by(invitation_token: params[:token])
    render :new && return if @manager

    redirect_to root_url, flash: {
      error: t('manager_invitations.flash.update.bad_token')
    }
  end

  def update
    @manager = Manager.find_by(invitation_token: params[:token])

    unless @manager
      redirect_to(
        root_url,
        flash: { error: t('manager_invitations.flash.update.bad_token') },
      ) && return
    end

    @manager.password_digest = nil
    if @manager.update(invitation_params)
      @manager.accept_invitation
      set_authentication_cookie(@manager)
      redirect_to(
        root_url,
        flash: { success: t('manager_invitations.flash.update.success') },
      ) && return
    end

    flash[:error] = t('manager_invitations.flash.update.error')
    render :new
  end

  private

  def invitation_params
    hash = params.permit(
      manager: %i[name password password_confirmation],
      service_referee: %i[name password password_confirmation]
    )
    hash = hash[:manager] || hash[:service_referee]
    hash[:password_confirmation] = "" if hash[:password_confirmation].nil?

    hash
  end

end

app/views/manager_invitations/new.html.erb
<h1><%= t('.title')%></h1>

<div class="form_invitation_creation">
  <%= form_for(@manager, url: invitations_managers_path) do |f| %>

    <% if f.object.errors.any? %>
      <div class="flash alert errors">
        <p>
          <%= t('.errors_count', count: f.object.errors.count) %>
        </p>
        <ul>
          <% f.object.errors.full_messages.each do |msg| %>
            <li>
              <%= msg %>
            </li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <%= hidden_field_tag :token, params[:token], readonly: true %>

    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>

    <div class="form-group">
      <%= f.label :password, t('.password') %>
      <%= f.password_field :password %>
    </div>

    <div class="form-group">
      <%= f.label :password_confirmation, t('.password_confirmation') %>
      <%= f.password_field :password_confirmation %>
    </div>

    <p class="submit-container">
      <%= f.submit t('.submit') %>
    </p>
  <% end %>

</div>