config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :entities, only: %i[new create]

  resources :managers, only: %i[new create destroy] do
    collection do
      # manager sessions
      get 'sessions/new', to: 'manager_sessions#new', as: :sign_in
      post 'sessions', to: 'manager_sessions#create'
      delete 'session', to: 'manager_sessions#destroy', as: :sign_out

      # manager invitations
      get 'invitations/:token',
          to: 'manager_invitations#new',
          as: :new_invitation
      patch 'invitations', to: 'manager_invitations#update'
    end
  end

  get 'passwords/lost', to: 'passwords#new', as: :new_password
  post 'passwords', to: 'passwords#create'
  get 'passwords/renew/:token', to: 'passwords#edit', as: :renew_password
  patch 'passwords', to: 'passwords#update'

  resources :services do
    resources :service_referees, only: %i[new create destroy]
    resources :assignations, only: [] do
      collection do
        delete :disable_notifications
        post :enable_notifications
      end
    end
  end
  get "/services/qrcode/:token",
      to: "services#qrcode",
      as: :service_qrcode
  get 'services/:id/:token', to: 'services#show'

  get "/entities/availabilities/:token",
      to: "entities#availabilities",
      as: :entity_availabilities
  get "/entities/qrcode/:token",
      to: "entities#qrcode",
      as: :entity_qrcode
  get "/services/availabilities/edit/:token",
      to: "services#edit_availabilities",
      as: :edit_availabilities
  patch "/services/availabilities/:token",
        to: "services#update_availabilities",
        as: :update_availabilities
  post "/services/notification_subscriptions/:token",
       to: "notification_subscriptions#create",
       as: :notification_subscriptions
  delete "/services/notification_subscriptions/:token",
         to: "notification_subscriptions#destroy",
         as: :delete_notification_subscriptions

  require 'sidekiq/web'
  require 'sidekiq/cron/web'
  # Sidekiq::Web.set :session_secret, Rails.application.credentials[:secret_key_base]
  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    ActiveSupport::SecurityUtils
      .secure_compare(
        ::Digest::SHA256.hexdigest(username),
        ::Digest::SHA256.hexdigest(ENV["SIDEKIQ_USERNAME"])
      ) &
      ActiveSupport::SecurityUtils.secure_compare(
        ::Digest::SHA256.hexdigest(password),
        ::Digest::SHA256.hexdigest(ENV["SIDEKIQ_PASSWORD"])
      )
  end
  mount Sidekiq::Web => '/sidekiq'

  get "/scanner", to: "pages#qrcode_scanner", as: "qrcode_scanner"
  root to: "pages#home"

end

app/models/service_referee.rb
class ServiceReferee < Manager

  has_many :assignations, dependent: :destroy
  has_many :services, through: :assignations, inverse_of: :service_referees

end

app/controllers/service_referees_controller.rb
class ServiceRefereesController < ApplicationController

  before_action :require_login

  def new
    @service = current_entity.services.where(id: params[:service_id]).first
    unless @service
      redirect_to root_url
      return
    end
    @referee = ServiceReferee.new(
      entity: current_entity,
      services: [@service]
    )
  end

  def create
    @service = current_entity.services.where(id: params[:service_id]).first
    unless @service
      redirect_to root_url
      return
    end

    @referee = current_entity.managers.where(
      email: create_manager_params[:email]
    ).first
    is_referee_creation = false
    unless @referee
      @referee = ServiceReferee.new(
        create_manager_params.merge(entity: current_entity)
      )
      is_referee_creation = true
    end

    if @service.service_referees.where(email: @referee.email).exists?
      flash[:error] = t('service_referees.flash.create.already_exists')
    else
      @referee.services << @service
      if @referee.save
        if is_referee_creation
          InvitationMailer.with(
            manager: @referee
          ).create_referee.deliver_later
        else
          InvitationMailer.with(
            service_referee: @referee,
            service: @service
          ).add_referee.deliver_later
        end
        flash[:success] = t('service_referees.flash.create.success')
      else
        flash[:error] = t('service_referees.flash.create.error')
        render :new
        return
      end
    end

    redirect_to(services_url)
  end

  def destroy
    @assignation = Assignation.where(
      service_id: params[:service_id],
      service_referee_id: params[:id]
    ).first
    if @assignation&.destroy
      if Assignation.where(service_referee_id: params[:id]).count == 0
        ServiceReferee.where(id: params[:id]).first.destroy
      end
      flash[:notice] = t('service_referees.flash.destroy.success')
    else
      flash[:notice] = t('service_referees.flash.destroy.error')
    end
    redirect_to new_service_service_referee_path
  end

  private

  def create_manager_params
    params
      .require(:service_referee)
      .permit(:name, :email, :contact_details)
      .merge(password_digest: "passw0rd")
  end

end

app/views/service_referees/new.html.erb
<h1><%= @service.name %></h1>

<% if @service.service_referees.any? %>
  <h2><%= t('.referees_title', service: @service.name) %></h2>
  <ul>
    <% @service.service_referees.each do |referee| %>
      <% if referee.persisted? %>
      <li>
        <%= referee.name %> &lt;<%= link_to referee.email, "mailto:#{referee.email}" %>&gt;&nbsp;-&nbsp;<%= link_to t('.delete'),
            service_service_referee_path(@service, referee),
            method: :delete,
            data: { confirm: t('.why_not') } %>
        <br />
        <%= simple_format(referee.contact_details) %>
      </li>
      <% end %>
    <% end %>
  </ul>
<% end %>

<h2><%= t('.title') %></h2>

<div class="form_service_referees_creation">
  <%= form_for @referee, url: service_service_referees_path(@service) do |f| %>

    <% if f.object.errors.any? %>
      <div class="flash alert errors">
        <p>
          <%= t('.errors_count', count: f.object.errors.count) %>
        </p>
        <ul>
          <% f.object.errors.full_messages.each do |msg| %>
            <li>
              <%= msg %>
            </li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= f.label :name, t('.name') %>
      <%= f.text_field :name %>
    </div>

    <div class="form-group">
      <%= f.label :email, t('.email') %>
      <%= f.email_field :email %>
    </div>

    <div class="form-group">
      <%= f.label :contact_details, t('.contact_details') %>
      <%= f.text_area :contact_details %>
    </div>

    <p class="submit-container">
      <%= f.submit t('.submit') %>
    </p>
  <% end %>

</div>